### ISSUE TITLE
OutOfBoundsException: Last Request Content-Type isn't application/json

### ISSUE THREAD

**Issue by iadj** [njasm/soundcloud#35]
This issue appears to be back. Requesting a `bodyObject` is returning a `OutOfBoundsException: Last Request Content-Type isn't application/json`. Last time this happened it was because of a quiet out of the blue SoundCloud API update.

**Comment by iadj** [comment]
Yep, looks like SoundCloud is returning their JSON requests with `Content-Type: HTML` :100:

**Comment by njasm** [comment]
@iadj hey. do you know if they already spotted that issue? is it still happening?

I didn't have the time yet to validate, but if they messed up again, I'm not very inclined in "putting more workarounds in the library" :/

**Comment by njasm** [comment]
@iadj did you have the time to re-validate this issue? no one else have commented on it. I believe it's fixed by now. can you confirm?

**Comment by iadj** [comment]
@njasm I just made a GET request and got `text/html` back again, so it looks like they haven't fixed it. I believe the only work-around necessary is to json decode the requested content regardless of content type.

**Comment by hubentom** [comment]
I am still getting this issue? @njasm can you comment on this?

**Comment by njasm** [comment]
I need to investigate the extent of the issue.
I'll be looking into maybe this weekend..

Can you guys tell me if that is happening in the authentication phase or does just happen in specific endpoints and/or HTTP Verbs ?

Can you guys provide me with code to replicate the issue? 
thanks

**Comment by hubentom** [comment]
$scFacade     = new SoundcloudFacade($sClientID, $sClientSecret, $sCallbackUri);
$oAccessToken = $scFacade->codeForToken($code)->bodyRaw();
$aAccessToken = json_decode($oAccessToken, true);

is fails in codeForToken... and when we retry with same code still fails (maybe because code has been used?) 

we have users connecting all the time (ALOT) and this happen randomly - its really hurting our app.
Anythign you can do would be appreciated - even a work around?

**Comment by njasm** [comment]
@hubentom  ok, sisnce it's randomly do you log the errors(stacktrace?) that you can also post here?
thanks..

Yes, if authorization code is used once, for sure that it's not reusable anymore.

@iadj you have that under the same phase, the authorization one? your you have the problem querying endpoints?  it's also random for you?

**Comment by hubentom** [comment]
production.ERROR: exception 'OutOfBoundsException' with message 'Last Request Content-Type isn't application/json.' in /var/www/html/vendor/njasm/soundcloud/src/Soundcloud/Request/Response.php:87 Stack trace:
#0 /var/www/html/vendor/njasm/soundcloud/src/Soundcloud/SoundcloudFacade.php(92): Njasm\Soundcloud\Request\Response->bodyObject()

**Comment by hubentom** [comment]
@njasm  --- still having this issue :( any word on this?

**Comment by hubentom** [comment]
@njasm I am in real trouble with this issue - happening randomly but too much

**Comment by ashishbaltech** [comment]
@njasm Getting Error 
**OutOfBoundsException: Last Request Content-Type isn't application/json**
How we can solve it ?

**Comment by njasm** [comment]
I Wasn't able to reporduce it.. I Sugest for now implement a try catch block around the code to authorize your users... and maybe implement a simple retry mechanism after x seconds?

I'll change the code to try to decode the payload to json, regarding the content-type.. but I need to find the best way to inform the calling code that the authentication did or did not take place.

Can you guys paste a var_dump($response->bodyRaw()) when the OutOfBoundsException is thrown, need to confirme if soundcloud is providing the right payload regarding the content type

**Comment by hubentom** [comment]
@njasm its seems its empty? $oAccessToken = $scFacade->codeForToken($code)->bodyRaw();

**Comment by njasm** [comment]
@hubentom  right, so when soundcloud does not provide any data, how should the library in your case should behave? how to notify the calling code, that there are not token?

ps - I keep my sugestion to wrap that code around a try catch block and pretty inform your users that your app wasn't able to authorize with soundcloud at the moment..

**Comment by njasm** [comment]
old one.. if still happening please feel free to re-open.
